name: 'data_lakehouse'
version: '1.0.0'
config-version: 2

profile: 'data_lakehouse_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_lakehouse:
    staging:
      +materialized: view
      +schema: staging
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold

vars:
  bronze_path: "data/bronze"
  silver_path: "data/silver"
  gold_path: "data/gold"
